version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
      
  microk8s-check:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Install microk8s
          command: |
            sudo snap install microk8s --classic
            sudo snap alias microk8s.kubectl kubectl
            echo 'export PATH="/snap/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Enable services
          command: |
            microk8s.start
            microk8s.enable dns dashboard
            microk8s.kubectl get all --all-namespaces
            sudo snap install helm --classic
            helm init --service-account default
            helm ls
            helm install --name wordpress stable/wordpress
            kubectl get services
            helm delete --purge wordpress

workflows:
  build_docker_image:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/   
    - microk8s-check:
        requires:
          - build